# Generated by Django 4.1.4 on 2023-01-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='no_review',
            field=models.IntegerField(default=0),
        ),
    ]
