# Generated by Django 4.1.4 on 2023-01-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_review_average_rating_review_no_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='active',
        ),
        migrations.RemoveField(
            model_name='review',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='no_review',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='no_review',
            field=models.IntegerField(default=0),
        ),
    ]
